### PR TITLE
Visual fixes

### LINKED ISSUE #65: Note preview datetime field enhancement
In main dashboard in note preview:
- timestamp should be visible
- timestamp font size should be smaller than it is now in dialog
- timestamp icon unnecessary

### LINKED ISSUE #70: Change the way of adding new task in todo note
- Remove enter a new task field
- Adding new task with empty field at the end of todo list

### LINKED ISSUE #71: Todo note icons enhancement
- all buttons should be relatively smaller
- change X icon to trash icon
- change "untick" task icon to something else

### PR DESCRIPTION
**Pull request by wkud**
Fixes #71 
Fixes #70  
Fixes #65

### CODE REVIEW

File: src/components/pages/Notes/Todo/TodoItem.js [hunk 1]
```diff
@@ -11,17 +11,33 @@ const TodoItem = props => {
         <Row>
           <Col xs='auto' className='ml-1 pr-0'>
             <Button
-              variant='success'
-              onClick={() => checkTask(task.id, !task.checked)}
-              className='button-shadow'>
-              <i className={`fas fa-${task.checked ? 'check' : 'times'} fa-fw`} />
+              variant=''
```
Comment (c1rcle) [inline src/components/pages/Notes/Todo/TodoItem.js:14]: This line is redundant.

**Review by c1rcle — CHANGES_REQUESTED** [review]

File: src/components/pages/Notes/Todo/TodoItem.js (hunk 1 above)
Comment (wkud) [reply src/components/pages/Notes/Todo/TodoItem.js:14]: without this line, border of the button gets blue tint (becouse primary variant is default)

Comment (c1rcle) [reply src/components/pages/Notes/Todo/TodoItem.js:14]: Alright, fair enough. I suppose it's the easiest way of fixing that problem. :D

**Review by c1rcle — APPROVED** [review]
