### PR TITLE
Bug fix

### LINKED ISSUE #34: User is able to make a login request when type dirty email
When user hit the login button there should be fired frontend validation

image

### LINKED ISSUE #35: Input password should be cleared after unsuccessful try of login

### LINKED ISSUE #36: Missing information for the user on register screen
On register screen, when the user enters login, password, repeat password he tries to hit the register button, but he can't and he is lost, there is no message at all.

### LINKED ISSUE #37: I broke something, it doesn't work anymore
image

### PR DESCRIPTION
**Pull request by filip-wan**
- [x] Fixes #34 
- [x] Fixes #35 
- [x] Fixes #36 
- [x] Fixes #37

### CODE REVIEW

File: src/components/pages/Registration/index.js [hunk 1]
```diff
@@ -22,17 +22,18 @@ const Registration = () => {
 
   const onTextChanged = name => ({ target }) => {
     const { validity, value } = target;
-    const isValid = validity.patternMismatch || validity.typeMismatch;
-    setState({ ...state, [name]: { value, isValid } });
+    const isInvalid = validity.patternMismatch || validity.typeMismatch;
+    console.log(name, isInvalid);
```
Comment (c1rcle) [inline src/components/pages/Registration/index.js]: That should be removed.

File: src/contexts/UserContext/dispatchAsync.js [hunk 2]
```diff
@@ -7,20 +7,18 @@ import checkTokenAction from './actions/checkTokenAction';
...
-      dispatch({ type: 'LOADING_START' });
-      registerAction(action)
+      registerAction(action, dispatch)
         .then(a => dispatch(a))
         .catch(err => console.log(err));
       break;
     case 'LOGIN':
       dispatch({ type: 'LOADING_START' });
-      loginAction(action)
+      loginAction(action, dispatch, dispatch)
```
Comment (c1rcle) [inline src/contexts/UserContext/dispatchAsync.js]: Shouldn't that last parameter be removed?

**Review by c1rcle — DISMISSED** [review]
Everything looks good! 😃

**Review by c1rcle — APPROVED** [review]
