### PR TITLE
Fix bugs

### LINKED ISSUE #64: Fix cut note title
In main dashboard in note preview title field should be higher

### PR DESCRIPTION
**Pull request by filip-wan**
- [x] Fixes #64

### CODE REVIEW

File: src/components/pages/Notes/Note.js [hunk 1]
```diff
@@ -9,13 +9,20 @@ import 'simplebar/dist/simplebar.min.css';
...
   const [, , { openDialog }] = useNotes();
   const [expanded, setExpanded] = useState(false);
-  const todoListDiv = content =>
-    JSON.parse(content).map(i => (
+  const todoListDiv = content => {
+    let parsedContent;
+    try {
+      parsedContent = JSON.parse(content);
+    } catch (error) {
+      parsedContent = [];
```
Comment (wkud) [inline src/components/pages/Notes/Note.js:17]: It would be nice to have some console.log here, to show that there was an error. What do you think?

**Review by wkud — APPROVED** [review]
