### PR TITLE
Fix hardcoded api url

### LINKED ISSUE #107: CRITICAL: hardcoded url
https://github.com/c1rcle/yellow-notes-frontend/blob/4d8b4625813a84663e47cba2f6c2a75870c94fd9/src/apis/yellowNotesApi.js#L3

### PR DESCRIPTION
**Pull request by wkud**
Fixes #107

### CODE REVIEW

**Review by c1rcle — DISMISSED** [review]

File: src/index.js [hunk 1]
```diff
@@ -3,5 +3,6 @@ import ReactDOM from 'react-dom';
 import App from './App';
 import 'bootswatch/dist/litera/bootstrap.min.css';
 import './styles/custom.css';
+require('dotenv').config();
```
Comment (c1rcle) [inline src/index.js]: Is this still needed?

**Review by c1rcle — DISMISSED** [review]

File: src/index.js (hunk 1 above)
Comment (wkud) [reply src/index.js]: nope

**Review by c1rcle — APPROVED** [review]
